### PR TITLE
update inago version to 0.2.2

### PR DESCRIPTION
**Pull request by Nesurion**

### CODE REVIEW

**Comment by Nesurion** [comment]
ping @giantswarm/cena

**Comment by xh3b4sd** [comment]
Veto. See open comments in https://github.com/giantswarm/inago/pull/242

**Comment by Nesurion** [comment]
@xh3b4sd RFR. Version bump to 0.2.2 instead of 0.2.1

**Comment by xh3b4sd** [comment]
LGTM

**Pull request merged**
